<?php
/**
 * Created by PhpStorm.
 * User: Fabian
 * Date: 10.10.2017
 * Time: 13:14
 */

namespace Calltree\Static_\NodeVisitor;


use PhpParser\Comment\Doc;
use PhpParser\Node;
use PhpParser\NodeTraverser;
use PhpParser\NodeVisitorAbstract;

class Cleaner extends NodeVisitorAbstract {

	public function leaveNode( Node $node ) {
		if($node instanceof  Node\Stmt\If_) {

			if(empty($node->stmts) && empty($node->else->stmts) && empty($node->elseifs)) {

				$p = new \PhpParser\PrettyPrinter\Standard();

				echo "removing empty IF block ".preg_replace('/\s+/', ' ', $p->prettyPrint([$node]))."\n";
				return NodeTraverser::REMOVE_NODE;
			}

		}

		if($node instanceof Node\Stmt\Nop) {
			return NodeTraverser::REMOVE_NODE;
		}

		if($node->getDocComment()) {
			$node->setDocComment(new Doc(''));
		}

		parent::leaveNode( $node ); // TODO: Change the autogenerated stub
	}
}